[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# === 添加或修改下面这两行 ===
optimizer = true
optimizer_runs = 200
#solc = "/opt/homebrew/Cellar/solidity/0.8.21/bin/solc"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "bridge-std/=src/HUB/abstracts/",
]
ffi = true
fs_permissions = [{ access = "read-write", path = "./data"}]
dotenv_path = ".env"
ignored_error_codes = [2018, 5667, 2072, 1878, 6321] 
# See more config options https://github.com/foundry-rs/foundry/tree/master/config
